[tool.poetry]
name = "nucleus-cdk-test"
version = "0.1.0"
description = "Test environment for Nucleus CDK with version-pinned dependencies"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

# Core scientific computing
numpy = "2.3.1"
pandas = "2.3.0"
scipy = "1.16.0"
matplotlib = "3.10.3"
scikit-image = "0.25.2"
seaborn = "0.13.2"

# Jupyter ecosystem
jupyterlab = "4.3.5"
ipython = "8.32.0"
ipykernel = "6.29.5"
ipywidgets = "8.1.5"
notebook = "7.3.2"

# Data processing and visualization
h5py = "3.14.0"
imageio = "2.37.0"
pillow = "11.3.0"
tifffile = "2025.6.11"

# Web and networking
requests = "2.32.3"
urllib3 = "2.3.0"

# Data formats and parsing
pyyaml = "6.0.2"
openpyxl = "3.1.5"
et-xmlfile = "2.0.0"

# Scientific computing utilities
networkx = "3.5"
statsmodels = "0.14.5"

# Visualization and plotting
bokeh = "3.7.3"
holoviews = "1.21.0"
hvplot = "0.11.3"
panel = "1.7.2"

# Security and authentication
cryptography = "45.0.5"
certifi = "2024.12.14"

# Text processing and markup
markdown = "3.8.2"
beautifulsoup4 = "4.13.3"
bleach = "6.2.0"

# Configuration and settings
pydantic = "2.11.7"
jsonschema = "4.23.0"

# Date and time
python-dateutil = "2.9.0.post0"
pytz = "2025.1"

# Utilities
attrs = "25.1.0"
tqdm = "4.67.1"
rich = "13.9.4"
packaging = "24.2"

# Async and concurrency
anyio = "4.8.0"
tornado = "6.5.1"

# Terminal and CLI
prompt-toolkit = "3.0.50"
colorama = "0.4.6"

# Data validation and types
typing-extensions = "4.12.2"
annotated-types = "0.7.0"

# HTTP and API
httpcore = "1.0.7"
httpx = "0.28.1"

# Database and ORM
sqlalchemy = "2.0.41"

# Image and media processing
pywavelets = "1.8.0"

# Nucleus CDK specific
nucleus-cdk = "0.3.0a1"
jupyter-bokeh = "4.0.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^4.0"
black = "^23.0"
isort = "^5.0"
flake8 = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py312']

[tool.isort]
profile = "black"
multi_line_output = 3 