name: vpin-test
channels:
  - conda-forge
dependencies:
  - python=3.13.5
  - numpy=2.3.1
  - scipy=1.16.0
  - matplotlib=3.10.3
  - h5py=3.14.0
  - ipympl=0.9.7
  - ipywidgets=8.1.5
  - jupyterlab=4.3.5
  - jupyterlab-myst=2.4.2
  - tqdm=4.67.1
  - scikit-image=0.25.2
  - hvplot=0.11.3
  - seaborn=0.13.2
  - timple=0.1.8
  - rich=14.0.0
  - pip
  - pip:
      - et-xmlfile==2.0.0
      - jupyter-bokeh==4.0.5
      - nucleus-cdk==0.3.0a1
      - openpyxl==3.1.5